Clean up temp directories in tpm2 enc/dec before calling exec
Or else, the on_exit() trap will never be called and we will end up with
lots of temp directories as leftover.

diff --git a/src/pins/tpm2/clevis-decrypt-tpm2 b/src/pins/tpm2/clevis-decrypt-tpm2
--- a/src/pins/tpm2/clevis-decrypt-tpm2
+++ b/src/pins/tpm2/clevis-decrypt-tpm2
@@ -159,4 +159,8 @@ if [ -n "$fail" ]; then
     exit 1
 fi
 
+# The on_exit() trap will not be fired after exec, so let's clean up the temp
+# directory at this point.
+[ -d "${TMP}" ] && rm -rf "${TMP}"
+
 exec jose jwe dec -k- -i- < <(echo -n "$jwk$hdr."; /bin/cat)
