tests: improve tang advertisement validation test
Test was flaky, failing in some situations in CI.

Changes:
- Output stderr from the test functions, so that it helps diagnosing
  eventual issues

- Use a different port before calling do_test, as sometimes it would
  error out complaining about address already in use

- Also add a small delay when starting the test server

diff --git a/src/pins/tang/tests/tang-validate-adv b/src/pins/tang/tests/tang-validate-adv
--- a/src/pins/tang/tests/tang-validate-adv
+++ b/src/pins/tang/tests/tang-validate-adv
@@ -34,7 +34,11 @@ do_test() {
 
     run_test_server "${port}" "${response}"
     cfg="$(printf '{"url":"localhost:%d"}' "${port}")"
-    echo foo | clevis encrypt tang "${cfg}" -y 2>"${stderr}"
+    if ! echo foo | clevis encrypt tang "${cfg}" -y 2>"${stderr}"; then
+        echo "Error (do_test) response: ${response}" >&2
+        [ -r "${stderr}" ] && cat "${stderr}" >&2
+        return 1
+    fi
 }
 
 do_test_with_adv() {
@@ -43,7 +47,11 @@ do_test_with_adv() {
     local stderr="${3:-/dev/stderr}"
 
     cfg="$(printf '{"url":"localhost:%d","adv":"%s"}' "${port}" "${adv}")"
-    echo foo | clevis encrypt tang "${cfg}" 2>"${stderr}"
+    if ! echo foo-adv | clevis encrypt tang "${cfg}" 2>"${stderr}"; then
+        echo "Error (do_test_with_adv) adv: ${adv} response: ${response}" >&2
+        [ -r "${stderr}" ] && cat "${stderr}" >&2
+        return 1
+    fi
 }
 
 validate_output() {
@@ -100,8 +108,8 @@ HTTP/1.0 500 Internal Server Error
 
 EOF
 
-# Tests where bind is expected to pass.
 for c in "${CASES}"/good-*; do
+    port=$(tang_new_random_port)
     STDERR="${c}".stderr
     do_test "${port}" "${c}" "${STDERR}"
     validate_output "${STDERR}"
@@ -109,6 +117,7 @@ done
 
 # Tests where bind is expected to fail (validate is still expected to succeed).
 for c in "${CASES}"/bad-*; do
+    port=$(tang_new_random_port)
     STDERR="${c}".stderr
     ! do_test "${port}" "${c}" "${STDERR}"
     validate_output "${STDERR}"
