tests: introduce common test functions shared between tests
Signed-off-by: Oldřich Jedlička <oldium.pro@gmail.com>

diff --git a/src/pins/tang/tests/tang-common-test-functions.in b/src/pins/tang/tests/tang-common-test-functions.in
--- a/src/pins/tang/tests/tang-common-test-functions.in
+++ b/src/pins/tang/tests/tang-common-test-functions.in
@@ -18,24 +18,16 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
+. tests-common-functions
+
 SOCAT="@SOCAT@"
 TANGD_KEYGEN="@TANGD_KEYGEN@"
 TANGD="@TANGD@"
 
-tang_error() {
-    echo "${1}" >&2
-    exit 1
-}
-
-tang_skip() {
-    echo "${1}" >&2
-    exit 77
-}
-
 tang_sanity_check() {
     [ -n "${SOCAT}" ] && [ -n "${TANGD_KEYGEN}" ] && \
         [ -n "${TANGD}" ] && return 0
-    tang_skip "tang is not enabled/supported. Check if you have met all the requirements"
+    skip_test "tang is not enabled/supported. Check if you have met all the requirements"
 }
 
 # Creates a tang adv to be used in the tests.
@@ -61,7 +53,7 @@ tang_remove_rotated_keys() {
     local basedir="${1}"
 
     [ -z "${basedir}" ] && \
-        tang_error "tang_remove_rotated_keys: please specify 'basedir'"
+        error "tang_remove_rotated_keys: please specify 'basedir'"
 
     local db="${basedir}/db"
 
@@ -80,7 +72,7 @@ tang_new_keys() {
     local sig_name="${3:-}"
     local exc_name="${4:-}"
 
-    [ -z "${basedir}" ] && tang_error "tang_new_keys: please specify 'basedir'"
+    [ -z "${basedir}" ] && error "tang_new_keys: please specify 'basedir'"
 
     local db="${basedir}/db"
     mkdir -p "${db}"
@@ -102,39 +94,6 @@ tang_new_keys() {
     return 0
 }
 
-# Find listening port of a process
-tang_find_port() {
-    local pid="${1}"
-
-    [ -z "${pid}" ] && \
-        tang_error "tang_find_port: please specify 'pid'"
-
-    local port
-    port=$(lsof -Pan -p "${pid}" -iTCP -sTCP:LISTEN -Fn | grep '^n.*:' | cut -d: -f2)
-    [ -n "${port}" ] && echo "${port}"
-}
-
-# Wait for the tang server to be operational.
-tang_wait_until_ready() {
-    tang_sanity_check
-    local pid="${1}"
-
-    [ -z "${pid}" ] && \
-        tang_error "tang_wait_until_ready: please specify 'pid'"
-
-    local max_timeout_in_s=5
-    local start elapsed
-    start="${SECONDS}"
-    while ! tang_find_port "${pid}" >/dev/null; do
-        elapsed=$((SECONDS - start))
-        if [ "${elapsed}" -gt "${max_timeout_in_s}" ]; then
-            tang_error "Timeout (${max_timeout_in_s}s) waiting for tang server"
-        fi
-        sleep 0.1
-        echo -n . >&2
-    done
-}
-
 # Start a test tang server.
 tang_run() {
     tang_sanity_check
@@ -142,10 +101,10 @@ tang_run() {
     local sig_name="${2:-}"
     local exc_name="${3:-}"
 
-    [ -z "${basedir}" ] && tang_error "tang_run: please specify 'basedir'"
+    [ -z "${basedir}" ] && error "tang_run: please specify 'basedir'"
 
     if ! tang_new_keys "${basedir}" "" "${sig_name}" "${exc_name}"; then
-        tang_error "Error creating new keys for tang server"
+        error "Error creating new keys for tang server"
     fi
 
     local KEYS="${basedir}/db"
@@ -159,15 +118,15 @@ tang_run() {
     pid=$!
 
     echo "${pid}" > "${pidfile}"
-    tang_wait_until_ready "${pid}"
-    tang_find_port "${pid}" > "${portfile}"
+    process_wait_until_port_ready "${pid}"
+    process_find_port "${pid}" "tang" > "${portfile}"
 }
 
 # Stop tang server.
 tang_stop() {
     tang_sanity_check
     local basedir="${1}"
-    [ -z "${basedir}" ] && tang_error "tang_stop: please specify 'basedir'"
+    [ -z "${basedir}" ] && error "tang_stop: please specify 'basedir'"
 
     local pidfile="${basedir}/tang.pid"
     [ -f "${pidfile}" ] || return 0
@@ -183,10 +142,10 @@ tang_stop() {
 
 tang_get_port() {
     local basedir="${1}"
-    [ -z "${basedir}" ] && tang_error "tang_get_port: please specify 'basedir'"
+    [ -z "${basedir}" ] && error "tang_get_port: please specify 'basedir'"
 
     local portfile="${basedir}/tang.port"
-    [ -f "${portfile}" ] || tang_error "tang_get_port: tang is not running"
+    [ -f "${portfile}" ] || error "tang_get_port: tang is not running"
 
     cat "${portfile}"
 }
@@ -197,7 +156,7 @@ tang_get_adv() {
     local port="${1}"
     local adv="${2:-/dev/stdout}"
 
-    [ -z "${port}" ] && tang_error "tang_get_adv: please specify 'port'"
+    [ -z "${port}" ] && error "tang_get_adv: please specify 'port'"
     curl -L -o "${adv}" "http://localhost:${port}/adv"
 }
 
@@ -217,6 +176,6 @@ run_test_server() {
     pid=$!
 
     echo "${pid}" > "${pidfile}"
-    tang_wait_until_ready "${pid}"
-    tang_find_port "${pid}" > "${portfile}"
+    process_wait_until_port_ready "${pid}"
+    process_find_port "${pid}" "tang" > "${portfile}"
 }
