template: add precondition checks during installation into initrd
Signed-off-by: Oldřich Jedlička <oldium.pro@gmail.com>

diff --git a/src/pins/file/initramfs.in b/src/pins/file/initramfs.in
--- a/src/pins/file/initramfs.in
+++ b/src/pins/file/initramfs.in
@@ -32,4 +32,6 @@ die() {
     exit "$code"
 }
 
-copy_exec @bindir@/clevis-decrypt-file || die 1 "@bindir@/clevis-decrypt-file not found"
+if [ -x @bindir@/clevis-decrypt-file ]; then
+    copy_exec @bindir@/clevis-decrypt-file || die 1 "Unable to copy @bindir@/clevis-decrypt-file to initrd image"
+fi
diff --git a/src/pins/template/initramfs.in b/src/pins/template/initramfs.in
--- a/src/pins/template/initramfs.in
+++ b/src/pins/template/initramfs.in
@@ -32,16 +32,20 @@ die() {
     exit $1
 }
 
-copy_exec @bindir@/clevis-decrypt-@pin@ || die 1 "@bindir@/clevis-decrypt-@pin@ not found"
-
-#%# Possibly you to need to install additional binaries:
+#%# Possibly you need to find additional binaries...
 #%#
 #%# find_binary() {
 #%#     bin_name="$1"
-#%#     resolved=$(which ${bin_name})
+#%#     resolved=$(command -v ${bin_name})
 #%#     [ -z "$resolved" ] && die 1 "Unable to find ${bin_name}"
 #%#     echo "$resolved"
 #%# }
-#%#
-#%# curl_bin=$(find_binary "curl")
-#%# copy_exec "${curl_bin}" || die 2 "Unable to copy ${curl_bin} to initrd image"
+
+if [ -x @bindir@/clevis-decrypt-@pin@ ]; then
+    copy_exec @bindir@/clevis-decrypt-@pin@ || die 1 "Unable to copy @bindir@/clevis-decrypt-@pin@ to initrd image"
+
+    #%# ...and install them
+    #%#
+    #%# curl_bin=$(find_binary "curl")
+    #%# copy_exec "${curl_bin}" || die 2 "Unable to copy ${curl_bin} to initrd image"
+fi
