LUKS tests need root to run
Some tests involving cryptsetup will fail if not ran with root --
observed in some Fedora Koji builds and also on Ubuntu --, so let's
run those tests only with root.

Our Travis CI runs with root, so the tests will continue running there.

diff --git a/src/luks/tests/tests-common-functions.in b/src/luks/tests/tests-common-functions.in
--- a/src/luks/tests/tests-common-functions.in
+++ b/src/luks/tests/tests-common-functions.in
@@ -23,6 +23,11 @@ error() {
     exit 1
 }
 
+skip_test() {
+    echo "${1}" >&2
+    exit 77
+}
+
 # We require cryptsetup >= 2.0.4 to fully support LUKSv2.
 # Support is determined at build time.
 luks2_supported() {
@@ -43,12 +48,17 @@ create_tang_adv() {
         | jose jws sig -I- -s "${TEMPLATE}" -k "${SIG}" -o "${adv}"
 }
 
-
 # Creates a new LUKS1 or LUKS2 device to be used.
 new_device() {
     local LUKS="${1}"
     local DEV="${2}"
     local PASS="${3}"
+
+    # Some builders fail if the cryptsetup steps are not ran as root, so let's
+    # skip the test now if not running as root.
+    if [ $(id -u) != 0 ]; then
+        skip_test "WARNING: You must be root to run this test; test skipped."
+    fi
 
     # Using a default password, if none has been provided.
     if [ -z "${PASS}" ]; then
@@ -75,6 +85,12 @@ new_device_keyfile() {
     local LUKS="${1}"
     local DEV="${2}"
     local KEYFILE="${3}"
+
+    # Some builders fail if the cryptsetup steps are not ran as root, so let's
+    # skip the test now if not running as root.
+    if [ $(id -u) != 0 ]; then
+        skip_test "WARNING: You must be root to run this test; test skipped."
+    fi
 
     if [[ -z "${KEYFILE}" ]] || [[ ! -f "${KEYFILE}" ]]; then
         error "Invalid keyfile (${KEYFILE})."
