luks: fix clevis luks unlock and add related tests
clevis luks unlock had a faulty logic to iterate through LUKS keyslots
in order to decrypt a device.

A clevis_luks_unlock_device() function was added to provide unlocking
capability, and it is now being used in clevis luks unlock.

Test were added as well.

diff --git a/src/luks/tests/tests-common-functions.in b/src/luks/tests/tests-common-functions.in
--- a/src/luks/tests/tests-common-functions.in
+++ b/src/luks/tests/tests-common-functions.in
@@ -56,7 +56,7 @@ new_device() {
 
     # Some builders fail if the cryptsetup steps are not ran as root, so let's
     # skip the test now if not running as root.
-    if [ $(id -u) != 0 ]; then
+    if [ "$(id -u)" != 0 ]; then
         skip_test "WARNING: You must be root to run this test; test skipped."
     fi
 
@@ -74,9 +74,9 @@ new_device() {
         return 0
     fi
 
-    fallocate -l16M "${DEV}"
-    local extra_options='--pbkdf pbkdf2 --pbkdf-force-iterations 1000'
-    cryptsetup luksFormat --type "${LUKS}" ${extra_options} --batch-mode \
+    fallocate -l64M "${DEV}"
+    cryptsetup luksFormat --type "${LUKS}" --pbkdf pbkdf2 \
+        --pbkdf-force-iterations 1000 --batch-mode \
         --force-password "${DEV}" <<< "${PASS}"
     # Caching the just-formatted device for possible reuse.
     cp -f "${DEV}" "${DEV_CACHED}"
@@ -90,7 +90,7 @@ new_device_keyfile() {
 
     # Some builders fail if the cryptsetup steps are not ran as root, so let's
     # skip the test now if not running as root.
-    if [ $(id -u) != 0 ]; then
+    if [ "$(id -u)" != 0 ]; then
         skip_test "WARNING: You must be root to run this test; test skipped."
     fi
 
@@ -98,9 +98,9 @@ new_device_keyfile() {
         error "Invalid keyfile (${KEYFILE})."
     fi
 
-    fallocate -l16M "${DEV}"
-    local extra_options='--pbkdf pbkdf2 --pbkdf-force-iterations 1000'
-    cryptsetup luksFormat --type "${LUKS}"  ${extra_options} --batch-mode \
+    fallocate -l64M "${DEV}"
+    cryptsetup luksFormat --type "${LUKS}" --pbkdf pbkdf2 \
+        --pbkdf-force-iterations 1000 --batch-mode \
         "${DEV}" "${KEYFILE}"
 }
 
@@ -112,4 +112,131 @@ pin_cfg_equal() {
          <(jq -S . < <(echo -n "${cfg2}"))
 }
 
+# Get a random port to be used with a test tang server.
+get_random_port() {
+    shuf -i 1024-65535 -n 1
+}
+
+# Removes tang rotated keys from the test server.
+tang_remove_rotated_keys() {
+    local basedir="${1}"
+
+    if [ -z "${basedir}" ]; then
+        echo "Please pass a valid base directory for tang"
+        return 1
+    fi
+
+    [ -z "${TANGD_UPDATE}" ] && skip_test "WARNING: TANGD_UPDATE is not defined."
+
+    local db="${basedir}/db"
+    local cache="${basedir}/cache"
+    mkdir -p "${db}"
+    mkdir -p "${cache}"
+
+    pushd "${db}"
+        find . -name ".*.jwk" -exec rm -f {} \;
+    popd
+
+    "${TANGD_UPDATE}" "${db}" "${cache}"
+    return 0
+}
+
+# Creates new keys for the test tang server.
+tang_new_keys() {
+    local basedir="${1}"
+    local rotate="${2}"
+
+    if [ -z "${basedir}" ]; then
+        echo "Please pass a valid base directory for tang"
+        return 1
+    fi
+
+    [ -z "${TANGD_KEYGEN}" ] && skip_test "WARNING: TANGD_KEYGEN is not defined."
+    [ -z "${TANGD_UPDATE}" ] && skip_test "WARNING: TANGD_UPDATE is not defined."
+
+    local db="${basedir}/db"
+    local cache="${basedir}/cache"
+    mkdir -p "${db}"
+
+    if [ -n "${rotate}" ]; then
+        pushd "${db}"
+            local k
+            k=$(find . -name "*.jwk" | wc -l)
+            if [ "${k}" -gt 0 ]; then
+                for k in *.jwk; do
+                    mv -f -- "${k}" ".${k}"
+                done
+            fi
+        popd
+    fi
+
+    "${TANGD_KEYGEN}" "${db}"
+    "${TANGD_UPDATE}" "${db}" "${cache}"
+
+    return 0
+}
+
+# Start a test tang server.
+tang_run() {
+    local basedir="${1}"
+    local port="${2}"
+
+    if [ -z "${basedir}" ]; then
+        echo "Please pass a valid base directory for tang" >&2
+        return 1
+    fi
+
+    if [ -z "${port}" ]; then
+        echo "Please pass a valid port for tang" >&2
+        return 1
+    fi
+
+    if ! tang_new_keys "${basedir}"; then
+        echo "Error creating new keys for tang server" >&2
+        return 1
+    fi
+
+    local KEYS="${basedir}/cache"
+    local inetd='--inetd'
+    [ "${SD_ACTIVATE##*/}" = "systemd-activate" ] && inetd=
+
+    local pid pidfile
+    pidfile="${basedir}/tang.pid"
+
+    "${SD_ACTIVATE}" ${inetd} -l "${TANG_HOST}":"${port}" \
+            -a "${TANGD}" "${KEYS}" &
+    pid=$!
+    echo "${pid}" > "${pidfile}"
+}
+
+# Stop tang server.
+tang_stop() {
+    local basedir="${1}"
+    local pidfile="${basedir}/tang.pid"
+    [ -f "${pidfile}" ] || return 0
+
+    local pid
+    pid=$(<"${pidfile}")
+    kill "${pid}"
+}
+
+# Wait for the tang server to be operational.
+tang_wait_until_ready() {
+   local port="${1}"
+   while ! curl --output /dev/null --silent --fail \
+                http://"${TANG_HOST}":"${port}"/adv; do
+       sleep 0.1
+       echo -n . >&2
+   done
+}
+
+# Get tang advertisement.
+tang_get_adv() {
+    local port="${1}"
+    local adv="${2}"
+
+    curl -o "${adv}" http://"${TANG_HOST}":"${port}"/adv
+}
+
+export TANG_HOST=127.0.0.1
 export DEFAULT_PASS='just-some-test-password-here'
