Avoid luksmeta corruption on clevis bind (#319)
When using long key information to be stored in luks metadata,
luksmeta save is not reporting the corruption of LUKs meta.
This change detects if issue occurs after luksmeta metadata save
and, in that case, restores the device. Fixes #181

Signed-off-by: Sergio Arroutbi Braojos <sarroutb@redhat.com>

diff --git a/src/luks/clevis-luks-common-functions.in b/src/luks/clevis-luks-common-functions.in
--- a/src/luks/clevis-luks-common-functions.in
+++ b/src/luks/clevis-luks-common-functions.in
@@ -448,6 +448,12 @@ clevis_luks1_save_slot() {
         echo "Error saving metadata to LUKSMeta slot ${SLOT} from ${DEV}" >&2
         return 1
     fi
+
+    if ! luksmeta test -d "${DEV}" 2>/dev/null >/dev/null ; then
+        echo "Error detected after saving metadata to LUKSMeta slot ${SLOT}, device ${DEV}" >&2
+        return 1
+    fi
+
     return 0
 }
 
