fix for different output from 'luksAddKey' command w/cryptsetup v2.0.2 (#135)
* changed method of determining slot used to not depend on locale-specific output

Resolves: #137 
Resolves: #108

diff --git a/src/luks/clevis-luks-bind.in b/src/luks/clevis-luks-bind.in
--- a/src/luks/clevis-luks-bind.in
+++ b/src/luks/clevis-luks-bind.in
@@ -28,6 +28,7 @@ function luks2_supported() {
     return @OLD_CRYPTSETUP@
 }
 
+
 function usage() {
     exec >&2
     echo
@@ -135,18 +136,46 @@ case "$KEY" in
  *) ! IFS= read -rd '' existing_key < "$KEY";;
 esac
 
-# Add the new key
+
+#Add the new key
 if [ -n "$SLT" ]; then
     cryptsetup luksAddKey --key-slot "$SLT" --key-file \
         <(echo -n "$existing_key") "$DEV"
 else
-    SLT="$(cryptsetup luksAddKey \
-        --key-file <(echo -n "${existing_key}") -v "$DEV" \
-        | sed -rn 's|^Key slot ([0-9]+) created\.$|\1|p')"
+    if [ $luks_type == "luks2" ]; then
+        readarray -t usedSlotsBeforeAddKey < <(cryptsetup luksDump "${DEV}" \
+            | sed -rn 's|^\s+([0-9]+): luks2$|\1|p')
+    else
+        readarray -t usedSlotsBeforeAddKey < <(cryptsetup luksDump "${DEV}" \
+            | sed -rn 's|^Key Slot ([0-7]): ENABLED$|\1|p')
+    fi
+    cryptsetup luksAddKey --key-file <(echo -n "${existing_key}") "$DEV"
 fi < <(echo -n "${key}")
 if [ $? -ne 0 ]; then
     echo "Error while adding new key to LUKS header!" >&2
     exit 1
+fi
+
+#Determine slot used by new key if a desired slot was not specified
+if [ -z "$SLT" ]; then
+    if [ "$luks_type" == "luks2" ]; then
+        readarray -t usedSlotsAfterAddKey < <(cryptsetup luksDump "${DEV}" \
+            | sed -rn 's|^\s+([0-9]+): luks2$|\1|p')
+    else
+        readarray -t usedSlotsAfterAddKey < <(cryptsetup luksDump "${DEV}" \
+            | sed -rn 's|^Key Slot ([0-7]): ENABLED$|\1|p')
+    fi
+    for i in "${usedSlotsAfterAddKey[@]}"; do
+        if [[ ! " ${usedSlotsBeforeAddKey[@]} " =~ " ${i} " ]]; then
+            SLT=$i
+            break
+        fi
+    done
+fi
+
+if [ -z "$SLT" ]; then
+	echo "Error while adding new key to LUKS header! Key slot is undefined." >&2
+	exit 1
 fi
 
 if [ "$luks_type" == "luks1" ]; then
