dracut: supply cryptsetup password through pipe (non-systemd boot)
Current Dracut integration for bootup without Systemd ignores all
cryptsetup options, which are usually handled by Dracut itself (like
reading /etc/crypttab). We need to hook into the Dracut cryptsetup process
in order to allow Dracut handling the options and us handling the password
only.

Dracut uses generated udev rules to create cryptsetup unlocking scripts
in initqueue/settled dynamically when the corresponding device appears. The
unlocking tries to unlock by the key file first and then by password read
from user.

We can hook into the key file reading stage by providing our own pipe and
send the password via the pipe similarly to how the initramfs-tools
clevisloop is doing it. There is one difference, though, we have only one
try to unlock, but that should be enough.

For the network pins (tang and sss/tang at the moment) we can move the
generated Dracut cryptsetup unlocking scripts to initqueue/online to
ensure the unlocking happens at the right time.

Signed-off-by: Oldřich Jedlička <oldium.pro@gmail.com>

diff --git a/src/luks/clevis-luks-common-functions.in b/src/luks/clevis-luks-common-functions.in
--- a/src/luks/clevis-luks-common-functions.in
+++ b/src/luks/clevis-luks-common-functions.in
@@ -1183,3 +1183,26 @@ clevis_luks_type() {
     fi
     echo "${luks_type}"
 }
+
+# clevis_kill_pid() kills process and its children in a portable way
+# Works with both procps ps and Busybox ps.
+function clevis_kill_pid() {
+    local pid="$1"
+    local child_pids
+
+    [ -z "${pid}" ] && return 1
+
+    child_pids="$({ ps -Ao pid,ppid 2>/dev/null || ps -o pid,ppid 2>/dev/null || ps -Al 2>/dev/null || ps -l ||
+        { echo 'clevis: unable to get list of processes' >&2; exit 1; }; } |
+        awk -v pid="$pid" '
+            NR==1 {
+                for (i=1; i<=NF; i++) if ($i == "PID") pid_col = i; else if ($i == "PPID") ppid_col = i
+                if (!pid_col || !ppid_col) { print "clevis: unable to find PID and/or PPID columns in ps output" | "cat >&2"; exit 1 }
+                next
+            }
+            { if ($ppid_col == pid) print $pid_col }')"
+
+    for kill_pid in $pid $child_pids; do
+        kill "$kill_pid" 2>/dev/null
+    done
+}
