tpm2: fix wrong expected value usage
Fix usage of uninitialized ${orig} value. Also test exactly the string
without having newlines added by echo.

Signed-off-by: Oldřich Jedlička <oldium.pro@gmail.com>

diff --git a/src/pins/tpm2/tests/pin-tpm2-tests b/src/pins/tpm2/tests/pin-tpm2-tests
--- a/src/pins/tpm2/tests/pin-tpm2-tests
+++ b/src/pins/tpm2/tests/pin-tpm2-tests
@@ -58,8 +58,8 @@ test_pcr_ids() {
     local expected_pcr_ids="${3}"
 
     local enc
-    if ! enc=$(echo "${orig}" | clevis encrypt tpm2 "${cfg}"); then
-        echo "${TEST}: encrypt failed for cfg: ${cfg}" >&1
+    if ! enc=$(echo -n "${orig}" | clevis encrypt tpm2 "${cfg}"); then
+        echo "${TEST}: encrypt failed for cfg: ${cfg}" >&2
         return 1
     fi
 
@@ -68,7 +68,7 @@ test_pcr_ids() {
               | jose fmt -j- -Og clevis -Og tpm2 -Og pcr_ids -u- 2>/dev/null)
 
     local dec
-    dec=$(echo "${enc}" | clevis decrypt)
+    dec="$(echo "${enc}" | clevis decrypt)"
 
     if [ "${orig}" != "${dec}" ]; then
         echo "${TEST}: decoded text (${dec}) does not match original one (${orig})" >&2
@@ -92,9 +92,11 @@ test_enc_dec() {
 }
 
 test_enc_dec '{}' || exit 1
-test_pcr_ids "${orig}" '{}' "" || exit 1
-test_pcr_ids "${orig}" '{                   }' "" || exit 1
-test_pcr_ids "${orig}" '{"key": "ecc"}' "" || exit 1
+test_pcr_ids "Hi" '{}' "" || exit 1
+test_pcr_ids "Hello" '{}' "" || exit 1
+test_pcr_ids "Hi" '{                   }' "" || exit 1
+test_pcr_ids "Hi" '{"key": "ecc"}' "" || exit 1
+test_pcr_ids "Hello" '{"key": "ecc"}' "" || exit 1
 
 # Issue #103: now let's try a few different configs with both strings and
 # arrays and check if we get the expected pcr_ids.
@@ -104,15 +106,17 @@ _default_pcr_bank=$(tpm2_getcap pcrs |
     awk '/^[[:space:]]*-[[:space:]]*([^:]+):[[:space:]]*\[[[:space:]]*[^][:space:]]/ \
              {split($0, m, /[-:[:space:]]+/); print m[2]; exit}')
 if [ -n "$_default_pcr_bank" ] && validate_pcrs "${_default_pcr_bank}" "4,16"; then
-    test_pcr_ids "${orig}" '{"pcr_ids": "16"}' "16" || exit 1
-    test_pcr_ids "${orig}" '{"pcr_ids": ["16"]}' "16"  || exit 1
-    test_pcr_ids "${orig}" '{"pcr_ids": "4,  16"}' "4,16" || exit 1
-    test_pcr_ids "${orig}" '{"pcr_ids": "4,16"}' "4,16" || exit 1
-    test_pcr_ids "${orig}" '{"pcr_ids": ["4,16"]}' "4,16" || exit 1
-    test_pcr_ids "${orig}" '{"pcr_ids": [4,16]}' "4,16" || exit 1
-    test_pcr_ids "${orig}" '{"pcr_ids": [4,  16]}' "4,16" || exit 1
-    test_pcr_ids "${orig}" '{"pcr_ids": ["4","16"]}' "4,16" || exit 1
-    ! test_pcr_ids "${orig}" '{"pcr_ids": ["4","16"]}' "foo bar" || exit 1
+    test_pcr_ids "Hi" '{"pcr_ids": "16"}' "16" || exit 1
+    test_pcr_ids "Hello" '{"pcr_ids": "16"}' "16" || exit 1
+    test_pcr_ids "Hi" '{"pcr_ids": ["16"]}' "16"  || exit 1
+    test_pcr_ids "Hi" '{"pcr_ids": "4,  16"}' "4,16" || exit 1
+    test_pcr_ids "Hi" '{"pcr_ids": "4,16"}' "4,16" || exit 1
+    test_pcr_ids "Hello" '{"pcr_ids": "4,16"}' "4,16" || exit 1
+    test_pcr_ids "Hi" '{"pcr_ids": ["4,16"]}' "4,16" || exit 1
+    test_pcr_ids "Hi" '{"pcr_ids": [4,16]}' "4,16" || exit 1
+    test_pcr_ids "Hi" '{"pcr_ids": [4,  16]}' "4,16" || exit 1
+    test_pcr_ids "Hi" '{"pcr_ids": ["4","16"]}' "4,16" || exit 1
+    ! test_pcr_ids "Hi" '{"pcr_ids": ["4","16"]}' "foo bar" || exit 1
 else
     echo "Skipping tests related to issue#103 because the combination of pcr_bank and PCRs is invalid" >&2
 fi
