dracut: added TPM 1.2 support for Dracut
Signed-off-by: Oldřich Jedlička <oldium.pro@gmail.com>

diff --git a/src/luks/dracut/clevis/clevis-password-unlocker.in b/src/luks/dracut/clevis/clevis-password-unlocker.in
--- a/src/luks/dracut/clevis/clevis-password-unlocker.in
+++ b/src/luks/dracut/clevis/clevis-password-unlocker.in
@@ -115,6 +115,7 @@ clevisloop() {
     local askpass_info
     local sleep_time
     local OLD_CRYPTTAB_SOURCE=""
+    local tpm1cfg_attempted=0
 
     while true; do
         # Re-get the askpass PID in case there are multiple encrypted devices
@@ -138,6 +139,11 @@ EOM
         [ "$CRYPTTAB_SOURCE" = "$OLD_CRYPTTAB_SOURCE" ] && continue
         OLD_CRYPTTAB_SOURCE="$CRYPTTAB_SOURCE"
 
+        if [[ " $pins " == *" tpm1 "* ]] && [ $tpm1cfg_attempted -eq 0 ]; then
+            tpm1cfg_attempted=1
+            do_configure_tpm1
+        fi
+
         if luks_decrypt "${CRYPTTAB_SOURCE}" "${PASSFIFO}"; then
             info "Unlocked ${CRYPTTAB_SOURCE} with clevis"
 
@@ -151,6 +157,24 @@ EOM
             sleep 5
         fi
     done
+}
+
+do_configure_tpm1() {
+    local tcsd_output=
+
+    [ -x @bindir@/clevis-decrypt-tpm1 ] && [ -f @libexecdir@/clevis-luks-tpm1-functions ] || return
+
+    . @libexecdir@/clevis-luks-tpm1-functions
+
+    info "Starting TCSD daemon"
+
+    if ! tcsd_output=$(start_tcsd 2>&1); then
+        if [ -n "$tcsd_output" ]; then
+            echo "Unable to start TCSD: $tcsd_output" | vwarn
+        else
+            warn "Unable to start TCSD"
+        fi
+    fi
 }
 
 mkdir -p /var/cache/clevis-disks
