[shell style] Implement usage by default redirect, not redirect from every echo
This way it is not easy to miss one and code looks cleaner.

diff --git a/src/clevis b/src/clevis
--- a/src/clevis
+++ b/src/clevis
@@ -34,11 +34,12 @@ while [ $# -gt 0 ]; do
     exe=`findexe "$cmd"` && exec "$exe" "$@"
 done
 
-echo >&2
-echo "Command '$cmd' is invalid" >&2
-echo >&2
-echo "Usage: clevis COMMAND [OPTIONS]" >&2
-echo >&2
+exec >&2
+echo
+echo "Command '$cmd' is invalid"
+echo
+echo "Usage: clevis COMMAND [OPTIONS]"
+echo
 
 max=0
 for f in "$0"-*; do
@@ -51,9 +52,9 @@ for f in "$0"-*; do
     [ -f "$f" -a -x "$f" ] || continue
     summ=`"$f" --summary 2>/dev/null` || continue
     f="${f##*/}"
-    printf "  %-*s %s\n" "$max" "${f//-/ }" "$summ" >&2
+    printf "  %-*s %s\n" "$max" "${f//-/ }" "$summ"
 done
 
-echo >&2
+echo
 
 exit 1
