Made error verbose when invalid bin/arg  specified
Now listing whole command that clevis wanted to run
after potential recursion and binding

diff --git a/src/clevis b/src/clevis
--- a/src/clevis
+++ b/src/clevis
@@ -35,6 +35,8 @@ while [ $# -gt 0 ]; do
 done
 
 echo >&2
+echo "Command '$cmd' is invalid" >&2
+echo >&2
 echo "Usage: clevis COMMAND [OPTIONS]" >&2
 echo >&2
 
